mode = "debug"
listen_address = ":8080"

[api]
path = "/api/v1"
host = "127.0.0.1:8000"
scheme = "http"

[paths]
swagger = "../mindwell-server/web"
avatars = "../mindwell-server/avatars"
assets = "./web/assets"
